// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XnesServer.Models;

namespace XnesServer.Migrations
{
    [DbContext(typeof(XnesContext))]
    [Migration("20221217210441_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XnesServer.Models.Cities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("XnesServer.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber");

                    b.Property<int>("Bank");

                    b.Property<int>("BankBranch");

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("CitiesId");

                    b.Property<int>("City");

                    b.Property<string>("FullName");

                    b.Property<string>("FullNameEnglish");

                    b.Property<string>("Tz");

                    b.HasKey("Id");

                    b.HasIndex("CitiesId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("XnesServer.Models.Customers", b =>
                {
                    b.HasOne("XnesServer.Models.Cities", "Cities")
                        .WithMany()
                        .HasForeignKey("CitiesId");
                });
#pragma warning restore 612, 618
        }
    }
}
